# ╔════════════════════════════════════════════════════════╗
# ║                                                        ║
# ║  ███╗   ███╗██╗███████╗███████╗    ███████╗███╗   ██╗  ║
# ║  ████╗ ████║██║██╔════╝██╔════╝    ██╔════╝████╗  ██║  ║
# ║  ██╔████╔██║██║███████╗█████╗      █████╗  ██╔██╗ ██║  ║
# ║  ██║╚██╔╝██║██║╚════██║██╔══╝      ██╔══╝  ██║╚██╗██║  ║
# ║  ██║ ╚═╝ ██║██║███████║███████╗    ███████╗██║ ╚████║  ║
# ║  ╚═╝     ╚═╝╚═╝╚══════╝╚══════╝    ╚══════╝╚═╝  ╚═══╝  ║
# ║  ██████╗ ██╗      █████╗  ██████╗███████╗              ║
# ║  ██╔══██╗██║     ██╔══██╗██╔════╝██╔════╝              ║
# ║  ██████╔╝██║     ███████║██║     █████╗                ║
# ║  ██╔═══╝ ██║     ██╔══██║██║     ██╔══╝                ║
# ║  ██║     ███████╗██║  ██║╚██████╗███████╗              ║
# ║  ╚═╝     ╚══════╝╚═╝  ╚═╝ ╚═════╝╚══════╝              ║
# ║                                                        ║
# ╚════════════════════════════════════════════════════════╝

# ==========================================================
# Global user config
# ==========================================================

[tools]
node = "22"
python = "3.13.5"
